djangoProject/mysite/Profile/urls.py
from django.shortcuts import render
from django.conf.urls import url
from . import views,models
# Create your views here.

app_name = 'Profile'

urlpatterns = [


    url(r'^$',views.profile, name='profile'),
    url(r'^(?P<user_id>[0-9]+)/$', views.items, name='users'),
    url(r'^sign_in/$', views.signin, name='signin'),
    url(r'^sign_up/$', views.signup, name='signup'),
    url(r'^edit/$', views.edit, name='edit'),
    url(r'^edit/(?P<id>[0-9]+)/$', views.edit_form, name='edit_person'),
    url(r'^delete/(?P<id>[0-9]+)/$', views.delete, name='delete')

]

djangoProject/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Profile.urls')),
]

djangoProject/mysite/Profile/models.py
from django.db import models
from django.http import HttpResponse

# Create your models here.

class PersonalProfile(models.Model):

    f_name = models.CharField(max_length=20)
    l_name = models.CharField(max_length=20)
    nick_name = models.CharField(max_length=20)
    age = models.CharField(max_length=25)


    def __str__(self):
        return self.f_name + ' ' + self.l_name


class Item(models.Model):

    profile = models.ForeignKey(PersonalProfile, on_delete=models.CASCADE)

    item_name = models.CharField(max_length=30)
    item_link = models.CharField(max_length=250)

djangoProject/mysite/Profile/forms.py
from django import forms

from .models import PersonalProfile

class Form(forms.ModelForm):
    class Meta:
        model = PersonalProfile
        fields = [
            "f_name",
            "l_name",
            "nick_name",
            "age"
        ]

djangoProject/mysite/Profile/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponseRedirect
from .models import PersonalProfile
from .forms import Form

# Create your views here.
def profile(request):
    all_profiles = PersonalProfile.objects.all()
    return render(request, 'Profile/frontend.html', {'all_users' : all_profiles})

def items(request,user_id):

    try:
        curr_user = PersonalProfile.objects.get(pk=user_id)
    except PersonalProfile.DoesNotExist:
        raise Http404('This user does not exist')

    return render(request, 'Profile/display.html', {'user' : curr_user})

def signin(request):


    return render(request, 'Profile/signin.html')

def signup(request):

    form = Form(request.POST or None)
    context = {
        "form":form,
    }


    if form.is_valid():
        print(form.cleaned_data.get('f_name'))
        instance = form.save(commit=False)
        instance.save()

    return render(request, 'Profile/signup.html',context)

def edit(request):

    all_to_edit = PersonalProfile.objects.all()

    context = {
        'profiles' : all_to_edit,
    }

    return render(request, 'Profile/edit.html' ,context)

def edit_form(request,id):

    instance = get_object_or_404(PersonalProfile, id=id)

    form = Form(request.POST or None, instance=instance)


    if form.is_valid():

        instance = form.save(commit=False)
        instance.save()

    context = {

        "instance":instance,
        "form":form

    }

    return render(request, 'Profile/signup.html',context)

def delete(request,id):

    instance = get_object_or_404(PersonalProfile,id=id)
    instance.delete()
    return profile(request)

djangoProject/mysite/Profile/templates/Profile/base.html
{% load staticfiles %}
<head>
    <meta name="viewport" content="width=device-width , initial-scale=1" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/icon?family=Satisfy" rel="stylesheet">
    <script
  src="https://code.jquery.com/jquery-2.2.4.min.js"
  integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
  crossorigin="anonymous"></script>
    <script crossorigin="anonymous" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <title>{% block title %}My page{% endblock %}</title>
</head>

<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#ase">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>

            </button>

            <a class="navbar-brand" href="{% url 'Profile:profile' %}">My site</a>
        </div>
    <!-- Items -->
        <div class="collapse navbar-collapse" id="ase">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{% url 'Profile:profile' %}">
                        <span class="glyphicon glyphicon-cd" aria-expanded="false" aria-hidden="true"></span>&nbsp; Albums
                    </a>
                </li>

                <li class="">
                    <a href="{% url 'Profile:profile' %}">
                        <span class="glyphicon glyphicon-ok" aria-expanded="false" aria-hidden="true"/></span>&nbsp; Music
                    </a>
                </li>

                <li class="">
                    <a href="{% url 'Profile:signin' %}">
                        <span class="glyphicon glyphicon-chevron-right" aria-expanded="false" aria-hidden="true"/></span>&nbsp; Sign in
                    </a>
                </li>

                <li class="">
                    <a href="{% url 'Profile:signup' %}">
                        <span class="glyphicon glyphicon-chevron-up" aria-expanded="false" aria-hidden="true"/></span>&nbsp; Sign up
                    </a>
                </li>

                <li class="">
                    <a href="{% url 'Profile:edit' %}">
                        <span class="glyphicon glyphicon-chevron-sun" aria-expanded="false" aria-hidden="true"/></span>&nbsp; Edit
                    </a>
                </li>

            </ul>
        </div>

    </div>
</nav>
{% block base %}
{% endblock %}

djangoProject/mysite/Profile/templates/Profile/display.html
{% extends 'Profile/base.html' %}

{% block title %}
User data
{% endblock %}


{% block base%}
<form method="POST" action="{% url 'Profile:delete' user.id %}">
                {% csrf_token %}
                <button type="submit">Delete</button>
</form>
{% for item in user.item_set.all %}
    <ul>
        <li><img src="{{ item.item_link }}" alt="no_img"/></li>
        <li>{{item.item_name}}</li>
    </ul>
{% endfor %}

{% endblock %}

djangoProject/mysite/Profile/templates/Profile/edit.html
<!DOCTYPE html>
<html>
    <head>
        {% extends 'Profile/base.html' %}
        {% block title %}Edit{% endblock %}
    </head>




   {% block base %}
  <body>
<ul>
    {% for user in profiles %}
    <li>
        <a href="{% url 'Profile:edit_person' user.id %}"><h2>{{ user.f_name }} {{ l_name }}</h2></a>
    </li>
    {% endfor %}

</ul>

</body>
{% endblock %}

</html>

djangoProject/mysite/Profile/templates/Profile/frontend.html
{% extends 'Profile/base.html' %}

<link rel="stylesheet" type="text/css" href="Profile/_Profile.css" />

{% block title %}
All users
{% endblock %}

{% block base %}
<body>
{% for user in all_users %}
    <ul>
        <li><a href="{% url 'Profile:users' user.id %}">{{user.f_name}} {{user.l_name}}</a></li>
    </ul>
{% endfor %}
</body>
{% endblock %}

djangoProject/mysite/Profile/templates/Profile/signin.html
<!DOCTYPE html>
<html>
<head>
    {% extends 'Profile/base.html' %}
    {% block title %}Sign in{% endblock %}
</head>
{% block base %}
<body>

</body>
{% endblock %}

</html>

djangoProject/mysite/Profile/templates/Profile/signup.html
{% extends 'Profile/base.html' %}
{% block base %}
<div class="col-sm-3 container ">
    <form method="POST" action="#">
        {% csrf_token %}
        <div class="form-group">
            <label for="f_name">Enter first name:</label>
            <input id="f_name" class="form-control" placeholder="First name" name="f_name">
        </div>

        <div class="form-group">
            <label for="l_name">Enter last name:</label>
            <input id="l_name" class="form-control" placeholder="Last name" name="l_name">
        </div>

        <div class="form-group">
            <label for="nick">Enter nickname:</label>
            <input id="nick" class="form-control" placeholder="Enter nickname" name="nick">
        </div>

        <div class="form-group">
            <label for="age">Enter age:</label>
            <input id="age" class="form-control" placeholder="Enter age" name="age">
        </div>

        <button type="submit" class="btn btn-default">Register</button>
        {{ form.as_p }}
    </form>
</div>
{% endblock %}

djangoProject/mysite/Profile/templates/base.html
{% load staticfiles %}
<head>
    <meta name="viewport" content="width=device-width , initial-scale=1" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/icon?family=Satisfy" rel="stylesheet">
<script
  src="https://code.jquery.com/jquery-2.2.4.min.js"
  integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
  crossorigin="anonymous"></script>
    <script crossorigin="anonymous" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <title>{% block title %}My page{% endblock %}</title>
</head>

<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#ase">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>

            </button>

            <a class="navbar-brand" href="{% url 'Profile:profile' %}">My site</a>
        </div>
    <!-- Items -->
        <div class="collapse navbar-collapse" id="ase">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{% url 'Profile:profile' %}">
                        <span class="glyphicon glyphicon-cd" aria-expanded="false" aria-hidden="true"></span>&nbsp; Albums
                    </a>
                </li>

                <li class="">
                    <a href="{% url 'Profile:profile' %}">
                        <span class="glyphicon glyphicon-ok" aria-expanded="false" aria-hidden="true"></span>&nbsp; Music
                    </a>
                </li>

                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-cd" aria-expanded="false" aria-hidden="true"></span>&nbsp; Albums
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>
{% block base %}
{% endblock %}

djangoProject/mysite/Profile/templates/display.html
{% extends 'base.html' %}

{% block title %}
User data
{% endblock %}


{% block base%}

{% for item in user.item_set.all %}
    <ul>
        <li><img src="{{ item.item_link }}" alt="no_img"/></li>
        <li>{{item.item_name}}</li>
    </ul>
{% endfor %}

{% endblock %}

djangoProject/mysite/Profile/templates/frontend.html
{% extends 'base.html' %}

{% block title %}
All users
{% endblock %}

{% block base %}
{% for user in all_users %}
    <ul>
        <li><a href="{% url 'Profile:users' user.id %}">{{user.f_name}} {{user.l_name}}</a></li>
    </ul>
{% endfor %}
{% endblock %}